### ISSUE TITLE
IE11: Content property is empty

### ISSUE THREAD

**Issue by TimeDropsSB** [webcomponents/template#38] opened 2018-04-06 18:49 UTC
Example: https://codepen.io/anon/pen/EEOjwL

In IE11, a `<template>`'s content after `document.importNode()` is empty and therefore, it is not possible to access elements within it.

**Comment by TimvdLippe** [comment] 2018-04-07 12:52
I can reproduce this issue in Chrome as well: http://jsbin.com/lajuyax/edit?html,console,output If you comment out the `<script src="webcomponentsjs/webcomponents-lite.js"></script>` it works again natively.

**Comment by TimvdLippe** [comment] 2018-04-10 18:09
Okay, so I was confused at first, but apparently this is an issue in ShadyDOM, because it does work if you comment the line with `ShadyDOM = { force: true };`: http://jsbin.com/jurayuw/edit?html,console,output Then we have one `childNode` in Chrome, while it has zero `childNodes` with ShadyDOM enabled.

The root issue is actually in https://github.com/webcomponents/shadydom/blob/10f5360fb14802d53bb8f7279d6479ee03ab3f9a/src/logical-mutation.js#L357-L375 where line 363 should also fast-path for `template`, because there are no Shadow roots in a template (normally). By doing so, we do a proper deep clone, because ShadyDOM would previously ignore that, as there are no nodes in `childNodes`.

After we fix that, we should come back to this issue and see if we fixed the `.content` not being there in IE11.

**Comment by TimvdLippe** [comment] 2018-05-22 18:33
This issue appears to be fixed now with https://github.com/webcomponents/shadydom/pull/224

**Closed as completed by TimvdLippe** 2018-05-22 18:33 UTC
